/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type AvailableRegionsWithDates = {
  /**
   * @type string
   */
  region: string
  /**
   * @type array
   */
  dates: string[]
}