/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { TeamStanding } from './TeamStanding.ts'

export type GetStandingsResponse = {
  /**
   * @type array
   */
  standings: TeamStanding[]
}