/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GetAvailableStandingsResponse } from './GetAvailableStandingsResponse.ts'

/**
 * @description Success
 */
export type StandingsGetAvailableStandingsEndpoints200 = GetAvailableStandingsResponse

export type StandingsGetAvailableStandingsEndpointsQueryResponse = StandingsGetAvailableStandingsEndpoints200

export type StandingsGetAvailableStandingsEndpointsQuery = {
  Response: StandingsGetAvailableStandingsEndpoints200
  Errors: any
}