/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GetDetailResponse } from './GetDetailResponse.ts'

export type StandingsGetDetailEndpointPathParams = {
  /**
   * @type string
   */
  date: string
  /**
   * @type string
   */
  filename: string
}

/**
 * @description Success
 */
export type StandingsGetDetailEndpoint200 = GetDetailResponse

export type StandingsGetDetailEndpointQueryResponse = StandingsGetDetailEndpoint200

export type StandingsGetDetailEndpointQuery = {
  Response: StandingsGetDetailEndpoint200
  PathParams: StandingsGetDetailEndpointPathParams
  Errors: any
}