/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GetRegionsResponse } from './GetRegionsResponse.ts'

/**
 * @description Success
 */
export type StandingsGetRegionsEndpoint200 = GetRegionsResponse

export type StandingsGetRegionsEndpointQueryResponse = StandingsGetRegionsEndpoint200

export type StandingsGetRegionsEndpointQuery = {
  Response: StandingsGetRegionsEndpoint200
  Errors: any
}