/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { WeatherForecast } from './WeatherForecast.ts'

export type WeatherForecastGet200 = WeatherForecast[]

export type WeatherForecastGetQueryResponse = WeatherForecastGet200

export type WeatherForecastGetQuery = {
  Response: WeatherForecastGet200
  Errors: any
}