/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type FeaturesRankingsModelsDetails = {
  /**
   * @type string | undefined
   */
  key?: string
  /**
   * @type string | undefined
   */
  filename?: string
}