/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { FeaturesRankingsModelsDetails } from './FeaturesRankingsModelsDetails.ts'

export type FeaturesRankingsModelsTeamStanding = {
  /**
   * @type string | undefined
   */
  standings?: string
  /**
   * @type string | undefined
   */
  points?: string
  /**
   * @type string | undefined
   */
  teamName?: string
  /**
   * @type array | undefined
   */
  roster?: string[]
  /**
   * @type object | undefined
   */
  details?: FeaturesRankingsModelsDetails
}