/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AvailableRegionsWithDates } from './AvailableRegionsWithDates.ts'

export type GetAvailableStandingsResponse = {
  /**
   * @type array
   */
  regionWithDates: AvailableRegionsWithDates[]
}