/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { StandingsGetAvailableStandingsGetAvailableStandingsResponse } from './StandingsGetAvailableStandingsGetAvailableStandingsResponse.ts'

export type StandingsGetAvailableStandingsEndpointsPathParams = {
  /**
   * @type string
   */
  region: string
}

/**
 * @description Success
 */
export type StandingsGetAvailableStandingsEndpoints200 = StandingsGetAvailableStandingsGetAvailableStandingsResponse

export type StandingsGetAvailableStandingsEndpointsQueryResponse = StandingsGetAvailableStandingsEndpoints200

export type StandingsGetAvailableStandingsEndpointsQuery = {
  Response: StandingsGetAvailableStandingsEndpoints200
  PathParams: StandingsGetAvailableStandingsEndpointsPathParams
  Errors: any
}