/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { FeaturesRankingsModelsTeamStanding } from './FeaturesRankingsModelsTeamStanding.ts'

export type StandingsGetStandingsGetStandingsResponse = {
  /**
   * @type array | undefined
   */
  standings?: FeaturesRankingsModelsTeamStanding[]
}