/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { StandingsGetStandingsGetStandingsResponse } from './StandingsGetStandingsGetStandingsResponse.ts'

export type StandingsGetStandingsEndpointPathParams = {
  /**
   * @type string
   */
  region: string
  /**
   * @type string
   */
  date: string
}

/**
 * @description Success
 */
export type StandingsGetStandingsEndpoint200 = StandingsGetStandingsGetStandingsResponse

export type StandingsGetStandingsEndpointQueryResponse = StandingsGetStandingsEndpoint200

export type StandingsGetStandingsEndpointQuery = {
  Response: StandingsGetStandingsEndpoint200
  PathParams: StandingsGetStandingsEndpointPathParams
  Errors: any
}