/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type StandingsGetAvailableStandingsGetAvailableStandingsResponse = {
  /**
   * @type array | undefined
   */
  dates?: string[]
}