/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { StandingsGetRegionsGetRegionsResponse } from './StandingsGetRegionsGetRegionsResponse.ts'

/**
 * @description Success
 */
export type StandingsGetRegionsEndpoint200 = StandingsGetRegionsGetRegionsResponse

export type StandingsGetRegionsEndpointQueryResponse = StandingsGetRegionsEndpoint200

export type StandingsGetRegionsEndpointQuery = {
  Response: StandingsGetRegionsEndpoint200
  Errors: any
}