/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Details } from './Details.ts'

export type TeamStanding = {
  /**
   * @type string
   */
  standings: string
  /**
   * @type string
   */
  points: string
  /**
   * @type string
   */
  teamName: string
  /**
   * @type array
   */
  roster: string[]
  /**
   * @type object
   */
  details: Details
}