/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type VrsrankingServerWeatherForecast = {
  /**
   * @type string | undefined, date
   */
  date?: string
  /**
   * @type integer | undefined, int32
   */
  temperatureC?: number
  /**
   * @type integer | undefined, int32
   */
  temperatureF?: number
  /**
   * @type string
   */
  summary?: string | null
}