/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type WeatherForecast = {
  /**
   * @type string, date
   */
  date: string
  /**
   * @type integer, int32
   */
  temperatureC: number
  /**
   * @type integer, int32
   */
  temperatureF: number
  /**
   * @type string
   */
  summary?: string | null
}