/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { VrsrankingServerWeatherForecast } from './VrsrankingServerWeatherForecast.ts'

export type WeatherForecastGet200 = VrsrankingServerWeatherForecast[]

export type WeatherForecastGetQueryResponse = WeatherForecastGet200

export type WeatherForecastGetQuery = {
  Response: WeatherForecastGet200
  Errors: any
}