/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import type {
  StandingsGetAvailableStandingsEndpointsQueryResponse,
  StandingsGetAvailableStandingsEndpointsPathParams,
} from '../../types/StandingsGetAvailableStandingsEndpoints.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const standingsGetAvailableStandingsEndpointsSuspenseQueryKey = (region: StandingsGetAvailableStandingsEndpointsPathParams['region']) =>
  [{ url: '/api/standings/available/:region', params: { region: region } }] as const

export type StandingsGetAvailableStandingsEndpointsSuspenseQueryKey = ReturnType<typeof standingsGetAvailableStandingsEndpointsSuspenseQueryKey>

/**
 * {@link /api/standings/available/:region}
 */
export async function standingsGetAvailableStandingsEndpointsSuspense(
  region: StandingsGetAvailableStandingsEndpointsPathParams['region'],
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<StandingsGetAvailableStandingsEndpointsQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/standings/available/${region}`,
    ...requestConfig,
  })
  return res
}

export function standingsGetAvailableStandingsEndpointsSuspenseQueryOptions(
  region: StandingsGetAvailableStandingsEndpointsPathParams['region'],
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const queryKey = standingsGetAvailableStandingsEndpointsSuspenseQueryKey(region)
  return queryOptions<
    ResponseConfig<StandingsGetAvailableStandingsEndpointsQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<StandingsGetAvailableStandingsEndpointsQueryResponse>,
    typeof queryKey
  >({
    enabled: !!region,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return standingsGetAvailableStandingsEndpointsSuspense(region, config)
    },
  })
}

/**
 * {@link /api/standings/available/:region}
 */
export function useStandingsGetAvailableStandingsEndpointsSuspense<
  TData = ResponseConfig<StandingsGetAvailableStandingsEndpointsQueryResponse>,
  TQueryKey extends QueryKey = StandingsGetAvailableStandingsEndpointsSuspenseQueryKey,
>(
  region: StandingsGetAvailableStandingsEndpointsPathParams['region'],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<ResponseConfig<StandingsGetAvailableStandingsEndpointsQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? standingsGetAvailableStandingsEndpointsSuspenseQueryKey(region)

  const query = useSuspenseQuery(
    {
      ...(standingsGetAvailableStandingsEndpointsSuspenseQueryOptions(region, config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}