/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import type { StandingsGetStandingsEndpointQueryResponse, StandingsGetStandingsEndpointPathParams } from '../../types/StandingsGetStandingsEndpoint.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const standingsGetStandingsEndpointSuspenseQueryKey = (
  region: StandingsGetStandingsEndpointPathParams['region'],
  date: StandingsGetStandingsEndpointPathParams['date'],
) => [{ url: '/api/standings/:region/:date', params: { region: region, date: date } }] as const

export type StandingsGetStandingsEndpointSuspenseQueryKey = ReturnType<typeof standingsGetStandingsEndpointSuspenseQueryKey>

/**
 * {@link /api/standings/:region/:date}
 */
export async function standingsGetStandingsEndpointSuspense(
  region: StandingsGetStandingsEndpointPathParams['region'],
  date: StandingsGetStandingsEndpointPathParams['date'],
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<StandingsGetStandingsEndpointQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/standings/${region}/${date}`,
    ...requestConfig,
  })
  return res
}

export function standingsGetStandingsEndpointSuspenseQueryOptions(
  region: StandingsGetStandingsEndpointPathParams['region'],
  date: StandingsGetStandingsEndpointPathParams['date'],
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const queryKey = standingsGetStandingsEndpointSuspenseQueryKey(region, date)
  return queryOptions<
    ResponseConfig<StandingsGetStandingsEndpointQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<StandingsGetStandingsEndpointQueryResponse>,
    typeof queryKey
  >({
    enabled: !!(region && date),
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return standingsGetStandingsEndpointSuspense(region, date, config)
    },
  })
}

/**
 * {@link /api/standings/:region/:date}
 */
export function useStandingsGetStandingsEndpointSuspense<
  TData = ResponseConfig<StandingsGetStandingsEndpointQueryResponse>,
  TQueryKey extends QueryKey = StandingsGetStandingsEndpointSuspenseQueryKey,
>(
  region: StandingsGetStandingsEndpointPathParams['region'],
  date: StandingsGetStandingsEndpointPathParams['date'],
  options: {
    query?: Partial<UseSuspenseQueryOptions<ResponseConfig<StandingsGetStandingsEndpointQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? standingsGetStandingsEndpointSuspenseQueryKey(region, date)

  const query = useSuspenseQuery(
    {
      ...(standingsGetStandingsEndpointSuspenseQueryOptions(region, date, config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}