/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from '@tanstack/react-query'
import type { StandingsGetStandingsEndpointQueryResponse, StandingsGetStandingsEndpointPathParams } from '../../types/StandingsGetStandingsEndpoint.ts'
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query'

export const standingsGetStandingsEndpointInfiniteQueryKey = (
  region: StandingsGetStandingsEndpointPathParams['region'],
  date: StandingsGetStandingsEndpointPathParams['date'],
) => [{ url: '/api/standings/:region/:date', params: { region: region, date: date } }] as const

export type StandingsGetStandingsEndpointInfiniteQueryKey = ReturnType<typeof standingsGetStandingsEndpointInfiniteQueryKey>

/**
 * {@link /api/standings/:region/:date}
 */
export async function standingsGetStandingsEndpointInfinite(
  region: StandingsGetStandingsEndpointPathParams['region'],
  date: StandingsGetStandingsEndpointPathParams['date'],
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<StandingsGetStandingsEndpointQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/standings/${region}/${date}`,
    ...requestConfig,
  })
  return res
}

export function standingsGetStandingsEndpointInfiniteQueryOptions(
  region: StandingsGetStandingsEndpointPathParams['region'],
  date: StandingsGetStandingsEndpointPathParams['date'],
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const queryKey = standingsGetStandingsEndpointInfiniteQueryKey(region, date)
  return infiniteQueryOptions<
    ResponseConfig<StandingsGetStandingsEndpointQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<StandingsGetStandingsEndpointQueryResponse>,
    typeof queryKey
  >({
    enabled: !!(region && date),
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return standingsGetStandingsEndpointInfinite(region, date, config)
    },
    initialPageParam: 1,
    getNextPageParam: (lastPage) => lastPage['pageNumber'],
    getPreviousPageParam: (firstPage) => firstPage['pageNumber'],
  })
}

/**
 * {@link /api/standings/:region/:date}
 */
export function useStandingsGetStandingsEndpointInfinite<
  TData = InfiniteData<ResponseConfig<StandingsGetStandingsEndpointQueryResponse>>,
  TQueryData = ResponseConfig<StandingsGetStandingsEndpointQueryResponse>,
  TQueryKey extends QueryKey = StandingsGetStandingsEndpointInfiniteQueryKey,
>(
  region: StandingsGetStandingsEndpointPathParams['region'],
  date: StandingsGetStandingsEndpointPathParams['date'],
  options: {
    query?: Partial<InfiniteQueryObserverOptions<ResponseConfig<StandingsGetStandingsEndpointQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? standingsGetStandingsEndpointInfiniteQueryKey(region, date)

  const query = useInfiniteQuery(
    {
      ...(standingsGetStandingsEndpointInfiniteQueryOptions(region, date, config) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<InfiniteQueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}