/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { StandingsGetRegionsEndpointQueryResponse } from '../../types/StandingsGetRegionsEndpoint.ts'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const standingsGetRegionsEndpointQueryKey = () => [{ url: '/api/standings/regions' }] as const

export type StandingsGetRegionsEndpointQueryKey = ReturnType<typeof standingsGetRegionsEndpointQueryKey>

/**
 * {@link /api/standings/regions}
 */
export async function standingsGetRegionsEndpoint(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<StandingsGetRegionsEndpointQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/standings/regions`,
    ...requestConfig,
  })
  return res.data
}

export function standingsGetRegionsEndpointQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = standingsGetRegionsEndpointQueryKey()
  return queryOptions<StandingsGetRegionsEndpointQueryResponse, ResponseErrorConfig<Error>, StandingsGetRegionsEndpointQueryResponse, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return standingsGetRegionsEndpoint(config)
    },
  })
}

/**
 * {@link /api/standings/regions}
 */
export function useStandingsGetRegionsEndpoint<
  TData = StandingsGetRegionsEndpointQueryResponse,
  TQueryData = StandingsGetRegionsEndpointQueryResponse,
  TQueryKey extends QueryKey = StandingsGetRegionsEndpointQueryKey,
>(
  options: {
    query?: Partial<QueryObserverOptions<StandingsGetRegionsEndpointQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? standingsGetRegionsEndpointQueryKey()

  const query = useQuery(
    {
      ...(standingsGetRegionsEndpointQueryOptions(config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}