/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from '@tanstack/react-query'
import type { StandingsGetRegionsEndpointQueryResponse } from '../../types/StandingsGetRegionsEndpoint.ts'
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query'

export const standingsGetRegionsEndpointInfiniteQueryKey = () => [{ url: '/api/standings/regions' }] as const

export type StandingsGetRegionsEndpointInfiniteQueryKey = ReturnType<typeof standingsGetRegionsEndpointInfiniteQueryKey>

/**
 * {@link /api/standings/regions}
 */
export async function standingsGetRegionsEndpointInfinite(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<StandingsGetRegionsEndpointQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/standings/regions`,
    ...requestConfig,
  })
  return res.data
}

export function standingsGetRegionsEndpointInfiniteQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = standingsGetRegionsEndpointInfiniteQueryKey()
  return infiniteQueryOptions<StandingsGetRegionsEndpointQueryResponse, ResponseErrorConfig<Error>, StandingsGetRegionsEndpointQueryResponse, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return standingsGetRegionsEndpointInfinite(config)
    },
    initialPageParam: 1,
    getNextPageParam: (lastPage) => lastPage['pageNumber'],
    getPreviousPageParam: (firstPage) => firstPage['pageNumber'],
  })
}

/**
 * {@link /api/standings/regions}
 */
export function useStandingsGetRegionsEndpointInfinite<
  TData = InfiniteData<StandingsGetRegionsEndpointQueryResponse>,
  TQueryData = StandingsGetRegionsEndpointQueryResponse,
  TQueryKey extends QueryKey = StandingsGetRegionsEndpointInfiniteQueryKey,
>(
  options: {
    query?: Partial<InfiniteQueryObserverOptions<StandingsGetRegionsEndpointQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? standingsGetRegionsEndpointInfiniteQueryKey()

  const query = useInfiniteQuery(
    {
      ...(standingsGetRegionsEndpointInfiniteQueryOptions(config) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<InfiniteQueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}