/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from '@tanstack/react-query'
import type { StandingsGetAvailableStandingsEndpointsQueryResponse } from '../../types/StandingsGetAvailableStandingsEndpoints.ts'
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query'

export const standingsGetAvailableStandingsEndpointsInfiniteQueryKey = () => [{ url: '/api/standings/available' }] as const

export type StandingsGetAvailableStandingsEndpointsInfiniteQueryKey = ReturnType<typeof standingsGetAvailableStandingsEndpointsInfiniteQueryKey>

/**
 * {@link /api/standings/available}
 */
export async function standingsGetAvailableStandingsEndpointsInfinite(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<StandingsGetAvailableStandingsEndpointsQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/standings/available`,
    ...requestConfig,
  })
  return res.data
}

export function standingsGetAvailableStandingsEndpointsInfiniteQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = standingsGetAvailableStandingsEndpointsInfiniteQueryKey()
  return infiniteQueryOptions<
    StandingsGetAvailableStandingsEndpointsQueryResponse,
    ResponseErrorConfig<Error>,
    StandingsGetAvailableStandingsEndpointsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return standingsGetAvailableStandingsEndpointsInfinite(config)
    },
    initialPageParam: 1,
    getNextPageParam: (lastPage) => lastPage['pageNumber'],
    getPreviousPageParam: (firstPage) => firstPage['pageNumber'],
  })
}

/**
 * {@link /api/standings/available}
 */
export function useStandingsGetAvailableStandingsEndpointsInfinite<
  TData = InfiniteData<StandingsGetAvailableStandingsEndpointsQueryResponse>,
  TQueryData = StandingsGetAvailableStandingsEndpointsQueryResponse,
  TQueryKey extends QueryKey = StandingsGetAvailableStandingsEndpointsInfiniteQueryKey,
>(
  options: {
    query?: Partial<InfiniteQueryObserverOptions<StandingsGetAvailableStandingsEndpointsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? standingsGetAvailableStandingsEndpointsInfiniteQueryKey()

  const query = useInfiniteQuery(
    {
      ...(standingsGetAvailableStandingsEndpointsInfiniteQueryOptions(config) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<InfiniteQueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}