/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type {
  StandingsGetAvailableStandingsEndpointsQueryResponse,
  StandingsGetAvailableStandingsEndpointsPathParams,
} from '../../types/StandingsGetAvailableStandingsEndpoints.ts'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const standingsGetAvailableStandingsEndpointsQueryKey = (region: StandingsGetAvailableStandingsEndpointsPathParams['region']) =>
  [{ url: '/api/standings/available/:region', params: { region: region } }] as const

export type StandingsGetAvailableStandingsEndpointsQueryKey = ReturnType<typeof standingsGetAvailableStandingsEndpointsQueryKey>

/**
 * {@link /api/standings/available/:region}
 */
export async function standingsGetAvailableStandingsEndpoints(
  region: StandingsGetAvailableStandingsEndpointsPathParams['region'],
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<StandingsGetAvailableStandingsEndpointsQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/standings/available/${region}`,
    ...requestConfig,
  })
  return res
}

export function standingsGetAvailableStandingsEndpointsQueryOptions(
  region: StandingsGetAvailableStandingsEndpointsPathParams['region'],
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const queryKey = standingsGetAvailableStandingsEndpointsQueryKey(region)
  return queryOptions<
    ResponseConfig<StandingsGetAvailableStandingsEndpointsQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<StandingsGetAvailableStandingsEndpointsQueryResponse>,
    typeof queryKey
  >({
    enabled: !!region,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return standingsGetAvailableStandingsEndpoints(region, config)
    },
  })
}

/**
 * {@link /api/standings/available/:region}
 */
export function useStandingsGetAvailableStandingsEndpoints<
  TData = ResponseConfig<StandingsGetAvailableStandingsEndpointsQueryResponse>,
  TQueryData = ResponseConfig<StandingsGetAvailableStandingsEndpointsQueryResponse>,
  TQueryKey extends QueryKey = StandingsGetAvailableStandingsEndpointsQueryKey,
>(
  region: StandingsGetAvailableStandingsEndpointsPathParams['region'],
  options: {
    query?: Partial<
      QueryObserverOptions<ResponseConfig<StandingsGetAvailableStandingsEndpointsQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? standingsGetAvailableStandingsEndpointsQueryKey(region)

  const query = useQuery(
    {
      ...(standingsGetAvailableStandingsEndpointsQueryOptions(region, config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}