/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import type { StandingsGetAvailableStandingsEndpointsQueryResponse } from '../../types/StandingsGetAvailableStandingsEndpoints.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const standingsGetAvailableStandingsEndpointsSuspenseQueryKey = () => [{ url: '/api/standings/available' }] as const

export type StandingsGetAvailableStandingsEndpointsSuspenseQueryKey = ReturnType<typeof standingsGetAvailableStandingsEndpointsSuspenseQueryKey>

/**
 * {@link /api/standings/available}
 */
export async function standingsGetAvailableStandingsEndpointsSuspense(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<StandingsGetAvailableStandingsEndpointsQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/standings/available`,
    ...requestConfig,
  })
  return res.data
}

export function standingsGetAvailableStandingsEndpointsSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = standingsGetAvailableStandingsEndpointsSuspenseQueryKey()
  return queryOptions<
    StandingsGetAvailableStandingsEndpointsQueryResponse,
    ResponseErrorConfig<Error>,
    StandingsGetAvailableStandingsEndpointsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return standingsGetAvailableStandingsEndpointsSuspense(config)
    },
  })
}

/**
 * {@link /api/standings/available}
 */
export function useStandingsGetAvailableStandingsEndpointsSuspense<
  TData = StandingsGetAvailableStandingsEndpointsQueryResponse,
  TQueryKey extends QueryKey = StandingsGetAvailableStandingsEndpointsSuspenseQueryKey,
>(
  options: {
    query?: Partial<UseSuspenseQueryOptions<StandingsGetAvailableStandingsEndpointsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? standingsGetAvailableStandingsEndpointsSuspenseQueryKey()

  const query = useSuspenseQuery(
    {
      ...(standingsGetAvailableStandingsEndpointsSuspenseQueryOptions(config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}