/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import type { StandingsGetRegionsEndpointQueryResponse } from '../../types/StandingsGetRegionsEndpoint.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const standingsGetRegionsEndpointSuspenseQueryKey = () => [{ url: '/api/standings/regions' }] as const

export type StandingsGetRegionsEndpointSuspenseQueryKey = ReturnType<typeof standingsGetRegionsEndpointSuspenseQueryKey>

/**
 * {@link /api/standings/regions}
 */
export async function standingsGetRegionsEndpointSuspense(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<StandingsGetRegionsEndpointQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/standings/regions`,
    ...requestConfig,
  })
  return res.data
}

export function standingsGetRegionsEndpointSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = standingsGetRegionsEndpointSuspenseQueryKey()
  return queryOptions<StandingsGetRegionsEndpointQueryResponse, ResponseErrorConfig<Error>, StandingsGetRegionsEndpointQueryResponse, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return standingsGetRegionsEndpointSuspense(config)
    },
  })
}

/**
 * {@link /api/standings/regions}
 */
export function useStandingsGetRegionsEndpointSuspense<
  TData = StandingsGetRegionsEndpointQueryResponse,
  TQueryKey extends QueryKey = StandingsGetRegionsEndpointSuspenseQueryKey,
>(
  options: {
    query?: Partial<UseSuspenseQueryOptions<StandingsGetRegionsEndpointQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? standingsGetRegionsEndpointSuspenseQueryKey()

  const query = useSuspenseQuery(
    {
      ...(standingsGetRegionsEndpointSuspenseQueryOptions(config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}