/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { WeatherForecastGetQueryResponse } from '../../types/WeatherForecastGet.ts'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const weatherForecastGetQueryKey = () => [{ url: '/WeatherForecast' }] as const

export type WeatherForecastGetQueryKey = ReturnType<typeof weatherForecastGetQueryKey>

/**
 * {@link /WeatherForecast}
 */
export async function weatherForecastGet(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<WeatherForecastGetQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/WeatherForecast`, ...requestConfig })
  return res
}

export function weatherForecastGetQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = weatherForecastGetQueryKey()
  return queryOptions<
    ResponseConfig<WeatherForecastGetQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<WeatherForecastGetQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return weatherForecastGet(config)
    },
  })
}

/**
 * {@link /WeatherForecast}
 */
export function useWeatherForecastGet<
  TData = ResponseConfig<WeatherForecastGetQueryResponse>,
  TQueryData = ResponseConfig<WeatherForecastGetQueryResponse>,
  TQueryKey extends QueryKey = WeatherForecastGetQueryKey,
>(
  options: {
    query?: Partial<QueryObserverOptions<ResponseConfig<WeatherForecastGetQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? weatherForecastGetQueryKey()

  const query = useQuery(
    {
      ...(weatherForecastGetQueryOptions(config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}