/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import type { WeatherForecastGetQueryResponse } from '../../types/WeatherForecastGet.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const weatherForecastGetSuspenseQueryKey = () => [{ url: '/WeatherForecast' }] as const

export type WeatherForecastGetSuspenseQueryKey = ReturnType<typeof weatherForecastGetSuspenseQueryKey>

/**
 * {@link /WeatherForecast}
 */
export async function weatherForecastGetSuspense(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<WeatherForecastGetQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/WeatherForecast`, ...requestConfig })
  return res
}

export function weatherForecastGetSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = weatherForecastGetSuspenseQueryKey()
  return queryOptions<
    ResponseConfig<WeatherForecastGetQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<WeatherForecastGetQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return weatherForecastGetSuspense(config)
    },
  })
}

/**
 * {@link /WeatherForecast}
 */
export function useWeatherForecastGetSuspense<
  TData = ResponseConfig<WeatherForecastGetQueryResponse>,
  TQueryKey extends QueryKey = WeatherForecastGetSuspenseQueryKey,
>(
  options: {
    query?: Partial<UseSuspenseQueryOptions<ResponseConfig<WeatherForecastGetQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? weatherForecastGetSuspenseQueryKey()

  const query = useSuspenseQuery(
    {
      ...(weatherForecastGetSuspenseQueryOptions(config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}